### ISSUE TITLE
No module named 'hart_backend'

### ISSUE THREAD

**Issue by maxin-cn** [mit-han-lab/hart#2]
This is great work and thanks for open-sourcing the related code. I ran the sample code but encountered the following error:
```
File "./hart-main/hart/modules/networks/basic_hart.py", line 10, in <module>
    import hart_backend.fused_kernels
ModuleNotFoundError: No module named 'hart_backend'
```
It seems that some codes are missing.

**Comment by kentang-mit** [comment]
Hi there,

Thank you for your comments! You may need to run this
```bash
cd hart/kernels && python setup.py install
```

Best,
Haotian

**Comment by maxin-cn** [comment]
Thanks~

**Comment by TanSongBai** [comment]
@kentang-mit 
when I run this command "cd hart/kernels && python setup.py install",  I encountered the following error. How can I solve it?
Traceback (most recent call last):
  File "/home/songbai/szu/code/hart-main/hart/kernels/setup.py", line 230, in <module>
    setuptools.setup(
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/install.py", line 97, in run
    self.do_egg_install()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/install.py", line 149, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 168, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 154, in call_command
    self.run_command(cmdname)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 19, in run
    self.build()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
    _build_ext.run(self)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by hrz2000** [comment]
> @kentang-mit when I run this command "cd hart/kernels && python setup.py install", I encountered the following error. How can I solve it? Traceback (most recent call last): File "/home/songbai/szu/code/hart-main/hart/kernels/setup.py", line 230, in setuptools.setup( File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/**init**.py", line 117, in setup return distutils.core.setup(**attrs) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup return run_commands(dist) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands dist.run_commands() File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands self.run_command(cmd) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command super().run_command(command) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command cmd_obj.run() File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/install.py", line 97, in run self.do_egg_install() File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/install.py", line 149, in do_egg_install self.run_command('bdist_egg') File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command self.distribution.run_command(command) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command super().run_command(command) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command cmd_obj.run() File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 168, in run cmd = self.call_command('install_lib', warn_dir=False) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 154, in call_command self.run_command(cmdname) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command self.distribution.run_command(command) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command super().run_command(command) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command cmd_obj.run() File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 19, in run self.build() File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build self.run_command('build_ext') File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command self.distribution.run_command(command) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command super().run_command(command) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command cmd_obj.run() File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run _build_ext.run(self) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run self.build_extensions() File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions build_ext.build_extensions(self) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions self._build_extensions_serial() File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial self.build_extension(ext) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 263, in build_extension _build_ext.build_extension(self, ext) File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension objects = self.compiler.compile( File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile _write_ninja_file_and_compile_objects( File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects _run_ninja_build( File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error compiling objects for extension

same error, Does anyone know how to solve this? thanks
