### ISSUE TITLE
Error about installing hart_backend.fused_kernels

### ISSUE THREAD

**Issue by TanSongBai** [mit-han-lab/hart#9]
When I used this command to install hart_backend, I encountered this error. How can I solve it?
`cd hart/kernels && python setup.py install`

`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/songbai/szu/code/hart-main/hart/kernels/setup.py", line 230, in <module>
    setuptools.setup(
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/install.py", line 97, in run
    self.do_egg_install()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/install.py", line 149, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 168, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 154, in call_command
    self.run_command(cmdname)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 19, in run
    self.build()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
    _build_ext.run(self)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/songbai/anaconda3/envs/hart/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension`

**Comment by Kathy-Peng** [comment]
hi getting the same error, the environment is not possible to set up

**Comment by hrz2000** [comment]
@kentang-mit Could you help us solve this problem?

**Comment by AmirMaEl** [comment]
I rewrote the kernels, and it worked for me.
1. insert the files 'rms_norm.py' , 'rms_norm..cu' and 'rms_norm.cpp' in '/hart/kernels/csrc'  
2. modify the path in 'rms_norm.py'
3. delete the line where you 'import hart_backend' in '/hart/modules/networks/basic_hart.py' and replace with 'from hart.kernels.csrc.rms_norm import rms_norm'

rms_norm.py:
```
import torch
import os
from torch.utils.cpp_extension import load

path = "/home/hart/hart/kernels/csrc/" #MODIFY THIS
# Load the CUDA extension at runtime
NVCC_FLAGS = [
    "-O2",
    "-std=c++17",
    "-DENABLE_BF16",
    "-U__CUDA_NO_HALF_OPERATORS__",
    "-U__CUDA_NO_HALF_CONVERSIONS__",
    "-U__CUDA_NO_BFLOAT16_OPERATORS__",
    "-U__CUDA_NO_BFLOAT16_CONVERSIONS__",
    "-U__CUDA_NO_BFLOAT162_OPERATORS__",
    "-U__CUDA_NO_BFLOAT162_CONVERSIONS__",
    "--expt-relaxed-constexpr",
    "--expt-extended-lambda",
    "--use_fast_math",
    "--threads=8",
]
CXX_FLAGS = ["-O3", "-std=c++17", "-fopenmp", "-lgomp"]

rms_norm_cuda = load(
    name="rms_norm",
    sources=[path +"rms_norm.cu",path+"rms_norm.cpp"],
    extra_cflags=CXX_FLAGS,
    extra_cuda_cflags=NVCC_FLAGS,
    verbose=True,
)

def rms_norm(output: torch.Tensor,input: torch.Tensor, weight: torch.Tensor, epsilon: float, use_quant: bool = False):
    hidden_size = input.shape[-1]
    output_dtype = torch.int8 if use_quant else input.dtype
    # output = torch.empty_like(input, dtype=output_dtype)

    rms_norm_cuda.rms_norm(output, input, weight, epsilon, use_quant)
    return output
```

rms_norm.cu:
```
#include <ATen/cuda/CUDAContext.h>
#include <cuda_fp16.h>
#include <torch/extension.h>

#include "./common/dispatch_utils.h"
#include "./common/reduction_utils.cuh"
#include "./common/utils.cuh"
#include "./layernorm/layernorm.h"

namespace vllm {
// TODO(woosuk): Further optimize this kernel.
template <typename scalar_t, typename out_type, bool use_quant>
__global__ void rms_norm_kernel(
    out_type *__restrict__ out,           // [..., hidden_size]
    const scalar_t *__restrict__ input,   // [..., hidden_size]
    const scalar_t *__restrict__ weight,  // [hidden_size]
    const float epsilon, const int num_tokens, const int hidden_size) {
  __shared__ float s_variance;
  float variance = 0.0f;

  for (int idx = threadIdx.x; idx < hidden_size; idx += blockDim.x) {
    const float x = (float)input[blockIdx.x * hidden_size + idx];
    variance += x * x;
  }
  variance = blockReduceSum<float>(variance);
  if (threadIdx.x == 0) {
    s_variance = rsqrtf(variance / hidden_size + epsilon);
  }
  __syncthreads();

  for (int idx = threadIdx.x; idx < hidden_size; idx += blockDim.x) {
    float x = (float)input[blockIdx.x * hidden_size + idx];
    if constexpr (use_quant) {
      out[blockIdx.x * hidden_size + idx] =
          float_to_int8_rn(((float)(x * s_variance)) * (float)(weight[idx]));
    } else {
      out[blockIdx.x * hidden_size + idx] =
          ((scalar_t)(x * s_variance)) * weight[idx];
    }
  }
}
}  // namespace vllm

void rms_norm(torch::Tensor &out,     // [..., hidden_size]
                              torch::Tensor &input,   // [..., hidden_size]
                              torch::Tensor &weight,  // [hidden_size]
                              float epsilon, bool use_quant) {
  int hidden_size = input.size(-1);
  int num_tokens = input.numel() / hidden_size;
  dim3 grid(num_tokens);
  dim3 block(std::min(hidden_size, 1024));
  const cudaStream_t stream = at::cuda::getCurrentCUDAStream();
  VLLM_DISPATCH_FLOATING_TYPES(input.scalar_type(), "rms_norm_kernel", [&] {
    if (use_quant) {
      vllm::rms_norm_kernel<scalar_t, int8_t, true><<<grid, block, 0, stream>>>(
          out.data_ptr<int8_t>(), input.data_ptr<scalar_t>(),
          weight.data_ptr<scalar_t>(), epsilon, num_tokens, hidden_size);
    } else {
      vllm::rms_norm_kernel<scalar_t, scalar_t, false>
          <<<grid, block, 0, stream>>>(
              out.data_ptr<scalar_t>(), input.data_ptr<scalar_t>(),
              weight.data_ptr<scalar_t>(), epsilon, num_tokens, hidden_size);
    }
  });
}
```

rms_norm.cpp:
```
#include <torch/extension.h>
#include <pybind11/pybind11.h>
#include <torch/extension.h>

#include "layernorm/layernorm.h"



// Bind the function to Python
PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("rms_norm", &rms_norm, py::arg("out"), py::arg("input"),
    py::arg("weight"), py::arg("epsilon"), py::arg("use_quant") = false,
    "Apply Root Mean Square (RMS) Normalization to the input tensor.");
}
```

hope that works for you :D
